apiVersion: v1
data:
  groups.yaml: |
  {{- range .Values.config.groups }}
    - name: {{ .name }}
      datasources:
        {{- range .datasources }}
        - {{ . }}
        {{- end }}
  {{- end }}
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-groups
